Traceback with variables (most recent call last):
  File "...omitted for tests only, abs path.../test_core.py", line 13, in check_
    f()
      kwargs = {'fmt': traceback_with_variables.core.Format(after=0, before=0, bri...ails=1, skip_files_except=[])}
      tb_reg = <bound method Reg.match_tb_text of <tests.test_utils.Reg object at 0x...omitted for tests only, obj id...>>
  File "...omitted for tests only, abs path.../dummies.py", line 92, in f
    return f(
      n = 10001
      s1 = 'short string with n: 10001'
      l1 = 'long string with 0..n: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1...9996, 9997, 9998, 9999, 10000'
      us = <exception while printing> Traceback (most recent call last):
          ...traceback_with_variables internal stacks...
          File "...omitted for tests only, abs path.../dummies.py", line 29, in __repr__
            raise ValueError("please don't print me")
        ValueError: please don't print me
        
  File "...omitted for tests only, abs path.../dummies.py", line 86, in f
    return 1 // (n * 0)
      n = 10000
      s1 = 'short string with n: 10000'
      l1 = 'long string with 0..n: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1... 9995, 9996, 9997, 9998, 9999'
      us = <exception while printing> Traceback (most recent call last):
          ...traceback_with_variables internal stacks...
          File "...omitted for tests only, abs path.../dummies.py", line 29, in __repr__
            raise ValueError("please don't print me")
        ValueError: please don't print me
        
builtins.ZeroDivisionError: integer division or modulo by zero