Traceback with variables (most recent call last):
  File "...omitted for tests only.../tests/test_core.py", line 106, in check
    f(arg)
      name = 'max_value...
      arg = 10000
      kwargs = {'fmt': <t...
  File "...omitted for tests only.../tests/dummies.py", line 12, in f
    return 1 // (n * 0)
      n = 10000
      s1 = 'short str...
      l1 = 'long stri...
      us = <exception while printing> Traceback (most recent call last):
          File "...omitted for tests only.../traceback_with_variables/core.py", line 212, in _to_cropped_str
            raw = print_(obj)
          File "...omitted for tests only.../tests/dummies.py", line 3, in __repr__
            raise ValueError("please don't print me")
        ValueError: please don't print me
        
builtins.ZeroDivisionError: integer division or modulo by zero