Traceback with variables (most recent call last):
  File "...omitted for tests only.../tests/test_core.py", line 106, in check
    f(arg)
      name = 'var_printers_0_0'
      arg = 10
      kwargs = {'fmt': <traceback_with_variables.core.Format object at 0x...omitted for tests only...>}
  File "...omitted for tests only.../tests/dummies.py", line 12, in f
    return 1 // (n * 0)
      n = 10
      s1 = 'short string with n: 10'
      l1 = 'long string with 0..n: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9'
      us = <exception while printing> Traceback (most recent call last):
          File "...omitted for tests only.../traceback_with_variables/core.py", line 212, in _to_cropped_str
            raw = print_(obj)
          File "...omitted for tests only.../tests/dummies.py", line 3, in __repr__
            raise ValueError("please don't print me")
        ValueError: please don't print me
        
builtins.ZeroDivisionError: integer division or modulo by zero