Traceback with variables (most recent call last):
  File "...omitted for tests only.../code.py", line...omitted for tests only..., in <module>
    f(a - 2)
      __loader__ = _frozen_importlib_external.SourceFileLoader(name='traceback_with_variables.main', path='...omitted for tests only.../main.py')
      __builtins__ = <module 'builtins' (built-in)>
      __package__ = None
      __spec__ = None
      __annotations__ = None
      __cached__ = None
      __name__ = '__main__'
      __file__ = '...omitted for tests only.../code.py'
      argparse = <module 'argparse' from '...omitted for tests only.../argparse.py'>
      f = <function f at 0x...omitted for tests only...>
      p = ArgumentParser(prog='code.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
      args = Namespace(a=3)
      a = 3
  File "...omitted for tests only.../code.py", line...omitted for tests only..., in f
    return 1 / m
      n = 1
      m = 0
builtins.ZeroDivisionError: division by zero
